---
name: ClangFormat Check
on:
  push:
    branches:
      - grass[0-9]+
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_protected != true }}
permissions: {}
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    env:
      TOOL_NAME: clang-format
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          persist-credentials: false
      - uses: DoozyX/clang-format-lint-action@11b773b1598aa4ae3b32f023701bca5201c3817d # v0.17
        with:
          source: "."
          clangFormatVersion: 15
          inplace: True
      - uses: ./.github/actions/create-suggestions
